version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ghost
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost
    ports:
      - "3306:3306"
    networks:
      - teste
  ghost:
    depends_on:
      - db
    image: ghost:1-alpine
    ports:
      - "2368:2368"
    restart: always
    networks:
      - teste
    environment:
      - GHOST_DB_HOST=db:3306
      - GHOST_DB_USER=ghost
      - GHOST_DB_PASSWORD=ghost
volumes:
  db_data:
networks:
  teste: